version: '3.0'
services:
  front-proxy:
    container_name: front-proxy
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./front-proxy:/etc/nginx/conf.d

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.development
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend:/app:cached
    stdin_open: true

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.development
    environment:
      - FIRESTORE_HOST=backend-firestore
    volumes:
      - backend-node-modules:/app/node_modules
      - ./backend:/app:cached
    stdin_open: true

  backend-firestore:
    container_name: backend-firestore
    image: yuyat/firestore-emulator

volumes:
  frontend-node-modules:
  backend-node-modules:
