version: '3.0'
services:
  front-proxy:
    container_name: front-proxy
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./front-proxy:/etc/nginx/conf.d

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.development
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend:/app:cached
    stdin_open: true

volumes:
  frontend-node-modules:
