steps:
  - id: Retrieve GITHUB_TOKEN
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud secrets versions access latest --secret=cloudbuild-terraform-github-token > GITHUB_TOKEN.txt
  - id: Plan
    name: hashicorp/terraform:0.13.0
    entrypoint: /bin/sh
    args:
      - -c
      - |
        set -eu
        set -o pipefail

        export GITHUB_TOKEN="$(cat GITHUB_TOKEN.txt)"

        ./scripts/terraform/setup.sh
        ./scripts/terraform/plan.sh
options:
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'GOOGLE_PROJECT=$PROJECT_ID'
    - 'BUILD_ID=$BUILD_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'TERRAFORM_ENVIRONMENT=gcp'
