name: backend

on:
  pull_request:
    branches:
      - master
    paths:
      - force-update-all-services.txt
      - .github/workflows/backend.yaml
      - backend/**
  push:
    branches:
      - master
    paths:
      - force-update-all-services.txt
      - .github/workflows/backend.yaml
      - backend/**

jobs:
  test:
    name: Run yarn test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('backend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn

      - run: yarn test

  lint:
    name: Run yarn lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('backend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn

      - run: yarn lint src/**/*.ts
