name: frontend

on:
  push:
    paths:
      - .github/workflows/frontend.yaml
      - frontend/**

jobs:
  test:
    name: Run yarn test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn test
